Avoid custom CoroutineScope, use lifecycleScope
This is an attempt to avoid an occasional error, where
some exception causes every subsequent coroutine to fail with
Error: cancelled.  Use the lifecycleScope provided by
androidx AppCompatActivity instead of a custom scope managed
BaseActivity.  Specify scope with every async or launch.